### ISSUE TITLE
[Bug]: (Android) Application Error!

### ISSUE THREAD

**Issue by omkar-tenkale** [ViscousPot/GitSync#344]
### Description

Sync fails 

### Minimal Reproduction

No idea

### Exception or Error

**Platform:** Android
**Device Model:** RMX3371
**OS Version:** 14 (SDK 34)
**App Version:** 1.7.60+1760

```
2025-07-14 19:59:03.016 [W] Sync: Sync Complete!
2025-07-14 19:59:02.992 [W] Sync: Pull Repo Failed
2025-07-14 19:59:02.990 [W] PullFromRepo: Fetching changes
  17: __start_thread
  16: _ZL15__pthread_startPv
  15: <unknown>
  14: <unknown>
  13: <unknown>
  12: <unknown>
  11: <unknown>
  10: <unknown>
   9: <unknown>
   8: <unknown>
   7: <unknown>
   6: <unknown>
   5: <unknown>
   4: <unknown>
   3: <unknown>
   2: <unknown>
   1: <unknown>
   0: <unknown>
Stack backtrace:

Error: corrupted loose reference file: FETCH_HEAD; class=Reference (4)

<asynchronous suspension>
#10     GitsyncService._sync (package:GitSync/gitsync_service.dart:113)
<asynchronous suspension>
#9      GitsyncService._sync.<anonymous closure> (package:GitSync/gitsync_service.dart:135)
<asynchronous suspension>
#8      GitManager.downloadChanges (package:GitSync/api/manager/git_manager.dart:638)
<asynchronous suspension>
#7      GitManager._runWithLock (package:GitSync/api/manager/git_manager.dart:36)
<asynchronous suspension>
#6      GitManager.downloadChanges.<anonymous closure> (package:GitSync/api/manager/git_manager.dart:644)
<asynchronous suspension>
#5      useDirectory (package:GitSync/api/helper.dart:129)
<asynchronous suspension>
#4      useDirectory.preUseAccess (package:GitSync/api/helper.dart:126)
<asynchronous suspension>
#3      GitManager.downloadChanges.<anonymous closure>.<anonymous closure> (package:GitSync/api/manager/git_manager.dart:645)
<asynchronous suspension>
#2      SseCodec.decodeObject (package:flutter_rust_bridge/src/codec/sse.dart:35)
#1      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:45)
2025-07-14 19:59:02.989 [E] PullFromRepo: #0      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:32)
2025-07-14 19:59:02.537 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.514 [W] Status: Getting local directory
2025-07-14 19:59:02.508 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.508 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.507 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.498 [W] Status: Getting local directory
2025-07-14 19:59:02.491 [W] Status: Getting local directory
2025-07-14 19:59:02.490 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.489 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.488 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.486 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.450 [W] RecentCommits: Recent commits retrieved
2025-07-14 19:59:02.304 [W] RecentCommits: .git folder found
2025-07-14 19:59:02.288 [W] Status: Getting local directory
2025-07-14 19:59:02.282 [W] RecentCommits:%2

**Comment by ViscousPot** [comment]
Sorry, this should have an option for an auto-fix. For now, you can manually delete the file "FETCH_HEAD" in the .git folder in you repository (folder may be hidden).
Then run a sync and the issue should fix it self.

Let me know if you continue to have issues here 👍🏾

**Comment by omkar-tenkale** [comment]
I tried auto fix, doesnt work
I deleted the FETCH_HEAD file, still doesnt work
I reinstalled the app, still on sync changes same error
It works from termux tho

I uninstalled and exited the beta programme as last resort

**Comment by ViscousPot** [comment]
Hey, thanks for reporting and I'm sorry you're having issues. I'm going to keep this open for now because I don't immediately have an idea of what's causing this.

Can I double check that you don't have obsidian-git enabled on your mobile vault or anything like that? (assuming you're even using GitSync for obsidian)

**Comment by ViscousPot** [comment]
OK, I'm going to close this for now, due to inactivity, but feel free to reopen and give more information if you are still facing the issue :)
